<?php

$public_key = 'pk_test_1234567';

$osm_type = 'product'; // $block->getData('osm_type');
$type = 'block';
$theme = 'white';
$logo_theme = 'color';
$brand_name = 'Nike';

$amount = 15400;

?>
<div class="smartpay-osm-<?php echo $osm_type ?>" data-prop-type="<?php echo $type ?>" data-prop-theme="<?php echo $theme ?>" data-prop-amount="<?php echo $amount ?>" data-prop-logo-theme="<?php echo $logo_theme ?>" data-prop-brand-name="<?php echo $brand_name ?>"></div>
<script src="https://js.smartpay.co/messaging.js" data-merchant="<?php echo $public_key; ?>" defer="defer"></script>